### ISSUE TITLE
Highly variable illuminance

### ISSUE THREAD

**Issue by V4ler1an** [EverythingSmartHome/everything-presence-lite#164] opened 2024-09-12 11:36 UTC
I raised [this issue](https://github.com/EverythingSmartHome/everything-presence-lite/issues/148) previously and was asked to update all the firmware, which i've done. Since then i've continued to see strange readings which has made using illuminance in my lighting automations impossible.

One example, my lounge and kitchen/diner are next to each other and i have the door open so I can see the light levels of both. Today they looked similar and the readings are this.
![image](https://github.com/user-attachments/assets/36f2d8e6-d836-47c9-8c36-77bee232ac41)

Then 30 minutes later, the light levels are still all pretty much unchanged (to my eyes) but these are now the reported levels:
![image](https://github.com/user-attachments/assets/e126da0a-77f0-4bb7-82ef-8fc84a37973b)

Today is full cloud, there were no periods of direct sun then cloud. It's been very consistent light levels.
Why are these readings so erratic? When I first received the EPLs they all read very similar and much lower readings, typically 0 -> 50 or 60 ish. My automations with illuminance were working great. Now i've had to disable them.

![image](https://github.com/user-attachments/assets/707c21e9-51e1-455f-881f-54cd05bccb4a)

![image](https://github.com/user-attachments/assets/cba88c9a-d206-4ef5-9274-543a3b970b06)

**Comment by sfranky** [comment] 2024-09-15 11:51
Same problem here, values are highly variable!

**Comment by sfranky** [comment] 2024-09-16 07:16
Is this maybe related to [issue 140](https://github.com/EverythingSmartHome/everything-presence-lite/issues/140) ?

**Comment by V4ler1an** [comment] 2024-09-16 08:59
Unquestionably. My problems also began with updating past the 1.0.6 firmware. I can see from https://github.com/EverythingSmartHome/everything-presence-lite/issues/140 they are making progress on finding a solution. Rather than downgrade I will wait for an update.

**Comment by EverythingSmartHome** [comment] 2024-09-16 09:40
Please update to 1.0.10 which was just pushed, it reverts the changes to the light sensor. I will close this one as it's a duplicate of https://github.com/EverythingSmartHome/everything-presence-lite/issues/140 but hopefully the new version should resolve

**Closed by EverythingSmartHome** 2024-09-16 09:40 UTC

**Comment by V4ler1an** [comment] 2024-09-16 09:55
Great, thank you.

**Comment by V4ler1an** [comment] 2024-09-21 16:52
> Please update to 1.0.10 which was just pushed, it reverts the changes to the light sensor. I will close this one as it's a duplicate of #140 but hopefully the new version should resolve

I'm not seeing this firmware update in HA like the previous. Is there a delay in pushing the update out? Or should I do the web based update?
