### ISSUE TITLE
ESPHome Setup: Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line.

### ISSUE THREAD

**Issue by chondro878** [EverythingSmartHome/everything-presence-lite#145] opened 2024-08-20 17:26 UTC
I am following the documentation for the Everything Presence Lite - This is my first ESP device, and I when trying to connect it to HA I am getting: “Can’t connect to ESP. Please make sure your YAML file contains an ‘api:’ line.” 

I've updated the yaml file with: 

```
# Your Wi-Fi SSID and password
wifi:
  ssid: "Wifi"
  password: "Password"

api:
  # No password specified here

# Optional: OTA (Over-The-Air) updates
ota:
  # Optional password for OTA updates if needed
```

And still get the same error. 

Certainly I'm not the only one running into this issue?
Edit: Looks like people are running into this issue and there "randomly" resolving. This has to be a bug: 
- https://github.com/EverythingSmartHome/everything-presence-lite/issues/68 
- https://community.home-assistant.io/t/looking-for-help-with-esphome-initial-setup/756820/10

**Comment by EverythingSmartHome** [comment] 2024-08-21 10:14
Hello, I think I already responded via email but this is a network issue (as the post you linked also shows) that needs resolving.

For others in future reading this, OP has Home Assistant on a different subnet to SSID they have connected their devices too. We have confirmed over email that OPs Home Assistant cannot ping devices on that SSID either because of a network misconfiguration or because of firewalls rules blocking access

Home Assistant needs to be able to communicate with devices across the network or the integration won't work

**Closed** 2024-10-08 11:30 UTC
